// Generated by Xata Codegen 0.23.5. Please do not edit.
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";
import { buildClient } from "@xata.io/client";

const tables = [
  {
    name: "partnerships",
    columns: [
      { name: "name", type: "text", notNull: true, defaultValue: "" },
      { name: "category", type: "text", notNull: true, defaultValue: "" },
      { name: "interests", type: "text", notNull: true, defaultValue: "" },
      { name: "contactInfo", type: "text", notNull: true, defaultValue: "" },
      { name: "status", type: "text", defaultValue: "pending" },
    ],
  },
  {
    name: "ai_logs",
    columns: [
      { name: "userMessage", type: "text" },
      { name: "aiResponse", type: "text" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Partnerships = InferredTypes["partnerships"];
export type PartnershipsRecord = Partnerships & XataRecord;

export type AiLogs = InferredTypes["ai_logs"];
export type AiLogsRecord = AiLogs & XataRecord;

export type DatabaseSchema = {
  partnerships: PartnershipsRecord;
  ai_logs: AiLogsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Juan-Carlos-Claridad-s-workspace-uaqao1.us-west-2.xata.sh/db/eliza-xyz",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
